### PR TITLE
Make sure relationship between baseline and wc is removed when wc is removed

### PR DESCRIPTION
**Pull request by frapell**
This is a fix for https://github.com/plone/plone.app.iterate/issues/77

### CODE REVIEW

**Comment by frapell** [comment]
@jenkins-plone-org please run jobs

**Comment by frapell** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Let me try to understand why it is done this way.

This [comment](https://github.com/plone/plone.app.iterate/blob/e97534bdd944fdd86d5d0ca35ba2bd2abb79d880/plone/app/iterate/dexterity/copier.py#L113-L114) in `_deleteWorkingCopyRelation` briefly explains why the relation is marked as broken, instead of immediately deleted:

> delete the wc reference keeping a reference to it **for its annotations** 

The `_deleteWorkingCopyRelation` method is called by the [`merge` method](https://github.com/plone/plone.app.iterate/blob/e97534bdd944fdd86d5d0ca35ba2bd2abb79d880/plone/app/iterate/dexterity/copier.py#L35-L42). In short:

```
baseline = self._getBaseline()
self._deleteWorkingCopyRelation()
new_baseline = self._replaceBaseline(baseline)
```

And `_replaceBaseline` has [this code](https://github.com/plone/plone.app.iterate/blob/e97534bdd944fdd86d5d0ca35ba2bd2abb79d880/plone/app/iterate/dexterity/copier.py#L80-L85) halfway through:

```
# copy annotations
wc_annotations = IAnnotations(self.context)
baseline_annotations = IAnnotations(baseline)

baseline_annotations.clear()
baseline_annotations.update(wc_annotations)
```

In other words, if `deleteWorkingCopyRelation` removes the relation completely, then there are no annotations that `_replaceBaseline` can restore: they are lost.

At least, that is what the comment _suggests_.

But I guess there are no annotations on the *relation*, but only on the working copy (`self.context` here, if I understand correctly). So I guess the change should be okay.

Except that the comment would need to be removed, as it is then outdated.

And it would be good to test this by creating a working copy, adding or changing some annotations on it, merging it, and checking if the annotations have been merged to the original.
Maybe enable WC support on images, checkout an image, visit all urls for scales, checkin, and see if the new annotations are there.
Or add a simple custom annotation with `bin/instance debug`.

**Comment by frapell** [comment]
@mauritsvanrees Mmm, you are totally right, not sure why there would be an annotation in the relation itself, but I will add the test cases you mention and see what happens

**Comment by ewohnlich** [comment]
I have attempted to implement the changes here as monkey patches to do some testing as I had the same issue. I get this error on checkin (ims.tools is the monkey patch location)

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 156, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 338, in publish_module
  Module ZPublisher.WSGIPublisher, line 256, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 62, in call_object
  Module plone.app.iterate.browser.checkin, line 50, in __call__
  Module plone.app.iterate.dexterity.policy, line 34, in checkin
  Module plone.app.iterate.dexterity.copier, line 42, in merge
  Module ims.tools.iterate, line 106, in _replaceBaseline
  Module plone.app.iterate.dexterity.copier, line 134, in _get_relation_to_baseline
plone.app.iterate.interfaces.CheckinException: Baseline has disappeared
```

If you look in `def merge` it first calls `self._deleteWorkingCopyRelation()` and then on the next line `new_baseline = self._replaceBaseline(baseline)`. Your file changes both of these to unindex the relation so indeed by the time `_replaceBaseline` is called the baseline has indeed disappeared. Is there a reason to have both of them try to delete the relation, or can the task be delegated to `_deleteWorkingCopyRelation`?

**Comment by frapell** [comment]
@ewohnlich Sorry, not quite sure what you are monkey patching there, or if maybe you have other custom code introducing noise... I would suggest you simply pull plone.app.iterate from this repository and use my branch `frapell-remove-relationship` to test. You can see that there are unit tests testing that this implementation does properly remove the relationship both for the check in as well for the cancel check out actions

**Comment by ewohnlich** [comment]
@frapell I was looking at the changed files in this PR with the intent to support the effort here internally before this version is actually released, but I misread one change as belonging to a different file. My apologies, your actual changes do in fact make sense :)

**Pull request merged**
