### PR TITLE
Use Plone 6.1 constraints in tox to avoid circular dependency error in Plone 6.0

### PR DESCRIPTION
**Pull request by wesleybl**
See: https://github.com/plone/plone.formwidget.recaptcha/pull/37#discussion_r1790443757

### CODE REVIEW

**Comment by wesleybl** [comment]
@mauritsvanrees @gforcada even though I removed the circular job in `.meta.toml` it still ran. Did I do something wrong?

**Comment by wesleybl** [comment]
hum I need to run meta again after updating `.meta.toml`

**Comment by davisagli** [comment]
@wesleybl This PR targets the master branch, but Plone 6.0 uses the 5.x branch. This change shouldn't be needed for Plone 6.1, which does not have the circular dependency problem. Right?

**Comment by wesleybl** [comment]
@davisagli I changed the PR to use Plone 6.1 constraints, where the circular dependency problem does not exist.

**Review by davisagli — APPROVED** [review]
@wesleybl Thanks!

**Pull request merged**
