### PR TITLE
No checkout via GET method

### PR DESCRIPTION
**Pull request by gotcha**
There should not be a way to checkout via GET method (CSRF)

### CODE REVIEW

**Comment by jensens** [comment]
Does this need to be ported to master?

**Comment by gotcha** [comment]
@jensens The plan is to fix tests first. Then to port to master if the branch gets accepted.

**Comment by gotcha** [comment]
@jensens Would you merge ?

**Comment by mauritsvanrees** [comment]
Thanks! I have released this in 2.1.16.

But do we really need yet another buildout config? The canonical way to run the tests is by using the [core development buildout](https://github.com/plone/buildout.coredev). I fear this new buildout config will be ignored, will start failing after a while, and then will trip up the next person who wants to do a fix and tries to use this buildout...
Do you mind if I remove this?

**Comment by gotcha** [comment]
Is the canonical way described somewhere ? I usually prefer the local buildout because I do not need to check out anything else.

**Comment by gforcada** [comment]
@gotcha the problem with local buildouts, is not only what @mauritsvanrees already pointed (that it will eventually be outdated) but also that your changes done in this package can make tests in other packages to fail, so it's always better to run it through buildout.coredev. You can run ``bin/test -s plone.app.iterate`` on buildout.coredev to check in-package failures and then let jenkins.plone.org (via a pull request) to check if there are interdependencies failures

**Comment by mauritsvanrees** [comment]
The canonical way is I think best described here: http://docs.plone.org/develop/coredev/docs/intro.html

**Pull request merged**
