### PR TITLE
Issue 1451 - Setted lock timeout to MAX_TIMEOUT to avoid baseline unwanted unlock after 10 minutes

### PR DESCRIPTION
**Pull request by rodfersou**
closes https://github.com/plone/Products.CMFPlone/issues/1451

### CODE REVIEW

**Comment by rodfersou** [comment]
I got stuck on how to test this PR, can someone help me with it?

**Comment by rodfersou** [comment]
* [p.a.iterate calls p.locking package](https://github.com/plone/plone.app.iterate/blob/2.1.x/plone%2Fapp%2Fiterate%2Finterfaces.py#L44)
* [p.locking instantiate a Zope2 webdav object](https://github.com/plone/plone.locking/blob/master/plone%2Flocking%2Flockable.py#L54)

This object control when [lock has timeout](https://github.com/zopefoundation/Zope/blob/master/src/webdav/LockItem.py#L136-L139)

**Comment by rodfersou** [comment]
There are no tests from the method ``isValid`` into Zope2 package to have an idea on how to do it.

**Comment by rodfersou** [comment]
@hvelarde @davisagli any idea on how to test this?

**Comment by rodfersou** [comment]
Jenkinks build http://jenkins.plone.org/job/pull-request-4.3/242/

**Comment by jensens** [comment]
You can always start a Jenkins job to test that your pull request (PR) does not break anything. 

To do so:
- go to http://jenkins.plone.org
- log in with your Github user
- click on the [Pull Request 5.0 job](http://jenkins.plone.org/job/pull-request-5.0/)
- click on the huge menu link ["Build with Parameters"](http://jenkins.plone.org/job/pull-request-4.3/build?delay=0sec) (here: Plone 4.3 link)
- paste the pull request URL into the text field (if multiple pull requests need to be combined in one run, then one PR URL per line)
- click on **Build**

Jenkins reports back to the pull request(s) on Github in the status box at the bottom.

In Plone we value a lot our testing suite, so we usually never merge pull requests if they have not been tested by Jenkins first.

**Comment by rodfersou** [comment]
@jensens no need to add into buildout.coredev checkouts.cfg?

**Comment by jensens** [comment]
if its merged then the person who merges needs to add plone.app.iterate to checkouts.cfg
while testing jenkins is friendly and does it for the test run automatically.

**Comment by rodfersou** [comment]
@jensens nice to know.. so it was already green when I did the commit into b.coredev and re-start jenkins..

**Comment by hvelarde** [comment]
@jensens can we have a new release?

**Comment by jensens** [comment]
I cant (no access at PyPI, so best you ask the @plone/release-team or one of the persons listed at the bottom of https://pypi.python.org/pypi/plone.app.iterate/3.1.5

**Comment by gforcada** [comment]
@hvelarde released: https://pypi.python.org/pypi/plone.app.iterate/2.1.15

**Comment by hvelarde** [comment]
@gforcada :beers:

**Pull request merged**
