### PR TITLE
Only one generic profile shown

### PR DESCRIPTION
**Pull request by gforcada**
Fixes https://github.com/plone/Products.CMFPlone/issues/1830

/cc @jensens I just copied & adapted the changes you made for plone.session, so I guess it is ok? I will try it locally

### CODE REVIEW

**Comment by jensens** [comment]
@gforcada should be enough

**Comment by gforcada** [comment]
Yes it does work, although that only hides the uninstall profile, there are still two plone.app.iterate profiles...

**Comment by gforcada** [comment]
So the second one is basically because CMFPlone depends on it, but given that both are exactly the same (they point to the same profiles folder) we can remove the deprecated profile and update CMFPlone to point to the default one, right?

**Comment by jensens** [comment]
the deprecated profile is ok imo, it should just be hidden as well.

**Pull request merged**
