### PR TITLE
Moved from product to profile. Plus some pep8 cleanup.

### PR DESCRIPTION
**Pull request by iham**
To remove the 
```
z2.installProduct(app, 'plone.app.iterate')
```
from the TestLayer's setUpZope() in `testing.py` i changed `configure.zcml`
```
<five:registerPackage package="." />
```
to:
```
<includeDependencies package="." />
```
according to what i learned using mr.bob's plone template for addons.

Please, let me know if its bullsh*t to do so.

I also did some pep8 on testing.py and setup.py. Mainly indentations and docstrings

### CODE REVIEW

**Comment by thet** [comment]
I wouldn't say "Moved to profile". Better something like "no need to register as Zope2 product. Be a package.". We will see, if there is no need - I started a Jenkins run: http://jenkins.plone.org/job/pull-request-5.0/958/
Also, includeDependencies (loads all ZCML files of all setup.py dependencies) does something else what five:registerPackage did (which makes Zope2 think it's a Zope2 Product).

When Jenkins goes gree, I'm +1 for merging.

BTW, what was the intention for this pull request? Did somethning break with ``z2.installProduct(app, 'plone.app.iterate') `` in testing.py?

**Comment by thet** [comment]
By the way, I found these references where five:registerpackage caused problems:
Probs with ZEO: https://dev.plone.org/ticket/6476
Probs with running tests: http://plone.293351.n2.nabble.com/Plone-4-tests-and-five-registerPackage-td4414896.html

**Comment by iham** [comment]
thanks thet!
i'll change that.

Nothing breaks with z2.installProduct()

As I'am new to testing and was comparing to my package testing built using mr.bob i found this - lets say "inconsistency". nothing serious.
plone.app.* or similar should be auto-included using z3c.autoinclude in setup.py and this little zcml-slug if possible to be "like we use it today". therefore i thought ill change it.

I also moved the name of the GenericSetup profile from "plone.app.iterate" to "default" as almost every other package i know uses this convention.

using this in a metadata.xml and typing `profile-plone.app.iterate:plone.app.iterate` instead of `profile-plone.app.iterate:default` felt very odd.

tests were fine on my local system. hope jenkins will be a friend ;)

**Comment by thet** [comment]
The profile renaming can be hairy - you have to check other core packages as well. Also it might break other packages depending on the old profile name...

**Comment by iham** [comment]
ok, then i'll add the default profile and comment the other name as "depricated" for the moment.

**Comment by iham** [comment]
fixed the profile naming.

as thet said it can be hairy, it was obvious to me why:
removing the profile name will lead to fail all tests.

i re-added it and kept both profiles `default` and `plone.app.iterate`.

**Comment by thet** [comment]
@iham not sure if this is worth the effort.... but I wouldn't keep two profile registrations, which are the same. That's prone to be forgotten and left and sometime no one knows about the purpose anymore...

I grep'd through all plone dependencies and found this (note the ``.`` stands for any character):

```
$ grep -Ri plone.app.iterate.plone.app.iterate
Products.CMFPlone/Products/CMFPlone/MigrationTool.py:99:    Addon(profile_id=u'plone.app.iterate:plone.app.iterate'),
plone.app.iterate/plone/app/iterate/configure.zcml:39:        profile="plone.app.iterate:plone.app.iterate"
plone.app.iterate/plone/app/iterate/testing.py:62:        applyProfile(portal, 'plone.app.iterate:plone.app.iterate')
plone.app.iterate/plone/app/iterate/testing.py:122:        applyProfile(portal, 'plone.app.iterate:plone.app.iterate')
```
That's not too much. Fixing in plone.app.iterate itself is easy. Fixing in CMFPlone will need a new major version of plone.app.iterate because of backwards incompatibility and CMFPlone depending on that. I'd also document the incompatibility like proposed here: https://github.com/plone/Products.CMFPlone/issues/1323
Still, it might break project specific integration/policy packages which install plone.app.iterate.

Actually, I'd leave the profile name as it is... any other opinions? /cc @jensens

**Comment by jensens** [comment]
what about adding second profile directory for ``name="plone.app.iterate" with just:
-  ``metadata.xml`` with dependency on default
- a profilemarker txt file 
- a setuphandler.py doing a  ``warning.warn('Do no use this profile anymore, use the default profile')``

and adding this as best practice to ``deprecation.rst`` in plone docs?

Would be cool to extend GenericSetup with reading an attribute ``deprecated="Use default profile."``.

**Comment by iham** [comment]
i like the idea! and will try to make the "old" profile install with a warning.

a deprecated attribute in GS would be awesome but i don't know enough about GS to implement it.
maybe a sprint topic ;)

**Comment by iham** [comment]
it would be even cooler to be able to bind a setupstep to a profile using zcml.

**Comment by jensens** [comment]
See also https://github.com/plone/Products.CMFPlone/issues/1070#issuecomment-142721292 for a different way to achieve the same without a second profile id. 

This is way more elegant, because we need only to register the same profile twice (not adding a new profile folder) under old and new name and then have an event handler checking if the old profile name was used and then do a warnings.warn in there if this is the case.

**Comment by jensens** [comment]
way better: use new ``post_handler`` - see https://github.com/zopefoundation/Products.GenericSetup/pull/24

**Comment by jensens** [comment]
Thank you for your contribution! In order to merge this Pull Request the Plone Foundation requires a Contributor Agreement from you. I can not find you in the list of contributors. This may be by accident and we forgot to add you there or because you never signed the contributor agreement. In first case send an e-mail to agreements@plone.org referencing this issue. In second case please visit https://plone.org/foundation/contributors-agreement and follow the instructions to become an Plone core contributor. Sorry for any inconvenience.

**Comment by iham** [comment]
After some big git issues and newbie errors i re-did my work on that and created a new pull request:
https://github.com/plone/plone.app.iterate/pull/20

**Pull request closed without merging**
