### PR TITLE
Issue 1541 - Fix exception for dexterity content types when get working copy

### PR DESCRIPTION
**Pull request by rodfersou**
closes https://github.com/plone/Products.CMFPlone/issues/1541

### CODE REVIEW

**Comment by rodfersou** [comment]
new build http://jenkins.plone.org/job/pull-request-4.3/260/

**Comment by rodfersou** [comment]
@hvelarde green

**Comment by hvelarde** [comment]
@plone/framework-team could you please take a look and merge?

this needs to be fixed in Plone 5 also, but the solution probably will be different.

**Comment by frapell** [comment]
This looks reasonable, @rodfersou how does this behave with AT content?

**Comment by rodfersou** [comment]
@frapell it work without problems.  Our [implementation of collective.cover work this way](https://github.com/collective/collective.cover/blob/master/src%2Fcollective%2Fcover%2Fevents.py#L54-L57).

**Comment by frapell** [comment]
@rodfersou right, but cover is a DX content type already, I don't remember what happens if you try to adapt an AT with IReferenceable, and was wondering if everything would continue to work fine

**Comment by rodfersou** [comment]
@frapell that piece of code at collective.cover adapts AT and DX content types associated with cover, not the cover itself.

It works fine with AT and DX content types to adapt with IReferenceable.

**Comment by jensens** [comment]
What is the state here? Sounds like we want this fix.

**Comment by hvelarde** [comment]
@jensens is tested, is working and needs a rebase.

**Comment by jensens** [comment]
@hvelarde perfect. hint: use the labels, thats what they are for.

**Comment by rodfersou** [comment]
@hvelarde @jensens rebased and green

**Comment by frapell** [comment]
@rodfersou Merged, thank you for this !

**Comment by rodfersou** [comment]
@frapell you are welcome

**Pull request merged**
