### PR TITLE
Use package permissions to protect views instead of more general ones

### PR DESCRIPTION
**Pull request by pbauer**
This was previously part of https://github.com/plone/plone.app.iterate/pull/96

These permissions are so far only used in Volto via `plone.restapi` but for some reason not in Classic-UI.
We might also add checks for these permissions to the actions via `browser/control.py`.

### CODE REVIEW

**Comment by pbauer** [comment]
Should we also change the rolemap-setup by adding `profiles/default/rolemap.xml` where we assign these to the respective roles and add a upgrade-step for that? It will make it easier to change them.

**Comment by pbauer** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
> Should we also change the rolemap-setup by adding `profiles/default/rolemap.xml` where we assign these to the respective roles and add a upgrade-step for that? It will make it easier to change them.

Yes! Sure.

**Comment by pbauer** [comment]
While implementing this I ran into something worth mentioning:

The permissions were previously setup and assigned to during startup even when `plone.app.iterate` is not installed. 
By switching to `rolemap.xml` the permission are setup but not assigned to any roles unless the package is installed.
Existing sites will get the rolemap installed by the upgrade-step.

With this change a site in which `plone.app.iterate` was **not** installed has different permissions than before (before with roles, after without roles). I don't think that has a negative effect in any scenario but I thought it is worth spelling it out here. 

plone.app.iterate is in the list of core-addons so the upgrade-step will be triggered by a plone-upgrade.

**Comment by pbauer** [comment]
@jenkins-plone-org please run jobs

**Comment by pbauer** [comment]
Test and merge together with https://github.com/plone/Products.CMFPlone/pull/3907

https://jenkins.plone.org/job/pull-request-6.0-3.8/3098/
https://jenkins.plone.org/job/pull-request-6.0-3.11/1052/
https://jenkins.plone.org/job/pull-request-6.1-3.8/159/
https://jenkins.plone.org/job/pull-request-6.1-3.12/172/

**Pull request merged**
