### PR TITLE
Fix checkin/checkout process for containers, since there was an annot…

### PR DESCRIPTION
**Pull request by sneridagh**
…ation left to reset (pos) on checkout and it broke the sections viewlet

### CODE REVIEW

**Comment by sneridagh** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
LGTM. Can be merged when the checks are green.

**Comment by sneridagh** [comment]
@mauritsvanrees is possible a 4.0.1 release?

**Comment by mauritsvanrees** [comment]
Sure. I released 4.0.1.  I will update coredev shortly.
For good measure, I created a branch 3.x as well, from before your major changes.

Minor thing, please do not add dashes in the news snippets. When pulled into the changelog, it would look like this:

```
Bug fixes:

- - Fix checkin/checkout process for containers, since there was an annotation left to "reset" (pos) on checkout and it broke the sections viewlet
    [sneridagh] (#93)
```

I have fixed it before the release.

**Pull request merged**
